- hosts: common
  gather_facts: False
  tasks:
  - name: install python 3 if needed
    raw: test -e /usr/bin/python || (sudo pacman -S python --noconfirm)

- hosts: common
  roles:
    - kewlfft.aur
    - common
