iso_install:
  hosts:
    arch_iso:
      ansible_host: 172.16.50.13
      ansible_user: root
      ansible_ssh_pass: root
      install_drive: /dev/nvme0n1

common:
  hosts:
    t14_fraise:
      ansible_host: 172.16.50.13
      hostname: "Fraise-T14"
    cm_rpi:
      ansible_host: 192.168.33.2
      hostname: "Fraise-RPI-CMB"
    dad_rpi:
      ansible_host: 172.16.50.132
      hostname: "Fraise-RPI-Home"
