- name: APP_TASK_TERMINAL - Enable system services
  systemd: 
    name: "{{ item }}"
    state: started
    enabled: true
  become: true
  loop: 
    - tlp.service
    - cups.service
    - cockpit.socket

- name: APP_TASK_TERMINAL - Disable powersaving for bluetooth module
  lineinfile:
    path: /etc/tlp.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: true
  loop:
    - { regexp: '^(# *)?USB_DENYLIST=', line: 'USB_DENYLIST="8087:0029"'}

- name: APP_TASK_TERMINAL - Copy over lldp file for Konica Minolta Office Printer
  copy:
    src: KOC759UX.ppd
    dest: /usr/share/cups/model/KOC759UX.ppd
    owner: root
    group: root
    mode: 0644
  notify: restart cups
  become: true

- name: APP_TASK_TERMINAL - Add office printer to system
  command: lpadmin -p "Konica_Office" -E -v lpd://10.206.0.112/print -m KOC759UX.ppd

##### needed for a new install (already have .zshrc in syncthing)
# - name: APP_TASK_TERMINAL - Setup oh-my-zsh
#   shell: /usr/share/oh-my-zsh/tools/install.sh --unattended
#   args:
#     creates: /home/{{ user.name }}/.oh-my-zsh

