- name: restart cups
  systemd:
    state: restarted
    name: cups
    enabled: yes
  become: true

- name: restart sshd
  systemd:
    state: restarted
    name: sshd
    enabled: yes
  become: true

- name: restart docker
  systemd:
    state: restarted
    name: docker
    enabled: yes
  become: true
