- name: install default packages
  pacman:
    name:
      - sudo
      - ntp
      - openssh
      - base
      - base-devel
      - networkmanager
    update_cache: yes
  become: true

- name: Give passwordless sudo access to wheel group
  copy:
    content: '%wheel ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/wheel
    validate: /usr/sbin/visudo --check --file=%s
  become: true

- name: sync time to ntp server
  command: ntpdate -u pool.ntp.org
  become: true

- name: start & enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - ntpd
    - sshd
    - NetworkManager
  become: true

- name: stop & disable networkd
  systemd:
    name: systemd-networkd
    state: stopped
    enabled: no
  become: true

- name: Install intel-ucode
  pacman:
    name:
      - intel-ucode # ucode for intel cpus
      - vulkan-intel # vulkan support for intel gpu's
    update_cache: yes
  when: ansible_processor[1].find('Intel') != -1
  become: true

- name: Install amd-ucode
  pacman:
    name:
      - amd-ucode # ucode for amd
      - vulkan-radeon # vulkan support for amd gpu's
      - radeontop # radeon gpu info
    update_cache: yes
  when: ansible_processor[1].find('AMD') != -1
  become: true

- name: set hostname
  hostname:
    name: "{{ hostname }}"
  become: true

- name: set hostname in hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: ^127.0.1.1
    line: '127.0.1.1 {{ hostname }} {{ hostname }}.localdomain'
  become: true

- name: generate en_US locale
  lineinfile:
    dest: /etc/locale.gen
    line: 'en_US.UTF-8 UTF-8'
  become: true

- name: generate locales
  command: locale-gen
  become: true
