- name: Rank Arch mirrors
  block:
    - name: Install the pacman-contrib package (for rankmirrors)
      pacman:
        name:
          - pacman-contrib
        update_cache: yes
    - name: Use rankmirrors to filter the fastest mirrors that support HTTPS
      shell: curl -s "https://archlinux.org/mirrorlist/?country=BE&country=FR&country=DE&country=NL&country=GB&protocol=https&ip_version=4&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 5 - > /etc/pacman.d/mirrorlist
      args:
        warn: false
  become: true
  tags:
    - mirrors
  when: ansible_architecture != "aarch64"

- name: create pacman mirrorlist for arm
  copy:
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: 0644
    content: |
      Server = http://mirror.archlinuxarm.org/$arch/$repo
  become: true
  when: ansible_architecture == "aarch64"

- name: copy pacman config
  template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: 644
  become: true

- name: disable compression of makepkg (aur packages)
  lineinfile:
    dest: /etc/makepkg.conf
    regexp: '^PKGEXT='
    line: "PKGEXT='.pkg.tar'"
  become: true

- name: install git & base-devel
  pacman:
    name:
      - git
      - base-devel
    update_cache: yes
    state: present
  become: true

- name: install paru
  aur:
    use: makepkg
    name: paru-bin
    state: present
