- block:
  - name: PACMAN - Install the pacman-contrib package (for rankmirrors)
    pacman:
      name:
        - pacman-contrib
      update_cache: yes
  - name: PACMAN - Use rankmirrors to filter the fastest mirrors that support HTTPS
    shell: curl -s "https://archlinux.org/mirrorlist/?country=BE&country=FR&country=DE&country=LU&country=NL&country=GB&protocol=https&ip_version=4&ip_version=6&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 5 - > /etc/pacman.d/mirrorlist
    args:
      warn: false
  become: true
  tags:
    - mirrors
  when: ansible_architecture != "aarch64"

- name: PACMAN - Create mirrorlist for arm
  copy:
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: 0644
    content: |
      Server = http://mirror.archlinuxarm.org/$arch/$repo
  become: true
  when: ansible_architecture == "aarch64"

- name: PACMAN - Set config items
  lineinfile:
    path: /etc/pacman.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: true
  loop:
    - { regexp: '^(# *)?Color', line: 'Color'}

- name: PACMAN - Enable multilib
  replace:
    dest: /etc/pacman.conf
    regexp: '\#\[multilib\]\n\#Include = /etc/pacman\.d/mirrorlist'
    replace: '[multilib]\nInclude = /etc/pacman.d/mirrorlist'
  become: true

- name: PACMAN - Disable compression of makepkg (aur packages)
  lineinfile:
    dest: /etc/makepkg.conf
    regexp: '^PKGEXT='
    line: "PKGEXT='.pkg.tar'"
  become: true

- name: PACMAN - Install git & base-devel
  pacman:
    name:
      - git
      - base-devel
    update_cache: yes
    state: present
  become: true

- name: PACMAN - Install paru
  aur:
    use: makepkg
    name: paru-bin
    state: present
