- name: install terminal apps
  aur:
    name:
      - android-tools # adb & fastboot
      - ansible # well you are running this playbook with it ¯\_(ツ)_/¯
      - bmon # network interface monitoring
      - bridge-utils # for libvirt & gns3
      - cups # printing services
      - docker
      - dmidecode # bios info
      - dnsmasq # needed for libvirt natting
      - ebtables # needed for libvirt natting
      - fping # fping -g 172.16.50.0/24
      - fwupd # fwupdmgr get-devices
      - glances # glances (htop replacement)
      - htop
      - inetutils # telnet
      - iperf3
      - libvirt # enhanced vm platform (running on top of qemu)
      - lldpd
      - mactelnet # mndp
      - modemmanager # for connecting modems
      - mtr # my traceroute
      - ncdu # storage info
      - neofetch # pretty sys info
      - nmap # portscans
      - oh-my-zsh-git # zsh the way it should be
      - paru-bin # aur helper
      - picocom # serial client
      - powerline-fonts-git # fonts for terminator
      - powertop # info on powerusage
      - qemu # vm platform
      - sipcalc # sipcalc 172.21.142.64/28
      - speedtest-cli # speedtest in terminal
      - sshpass # used for ansible
      - streamlink # get livestreams in VLC or other client
      - syncthing # sync config files
      - terminator # terminal emulator
      - tlp # battery life optimizations (install and forget)
      - unzip
      - usbutils # lsusb
      - vim
      - wget
      - whois # info on domain owner
      - wireguard-tools # used to create wireguard tunnel
      - wpa_supplicant # use for wifi connection
      - youtube-dl # download videos from the net
      - zsh # shell

- name: enable services
  service:
    name: "{{ item }}"
    enabled: yes
  become: true
  loop:
    - docker
    - libvirtd

##### needed for a new install (already have .zshrc in syncthing)
# - name: setup oh-my-zsh
#   shell: /usr/share/oh-my-zsh/tools/install.sh --unattended
#   args:
#     creates: /home/{{ user.name }}/.oh-my-zsh

- name: set default shell of user to zsh
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh
  become: true
