- name: TERMINAL - install terminal apps
  kewlfft.aur.aur:
    name:
      - android-tools # adb & fastboot
      - cups # printing services
      - dmidecode # bios info
      - fwupd # fwupdmgr get-devices
      - htop # hardware usage/processes in cli
      - gdu # storage info (ncdu alternative)
      - neofetch # pretty sys info
      - oh-my-zsh-git # zsh the way it should be
      - paru-bin # aur helper
      - powertop # info on powerusage
      - syncthing # sync config files
      - tlp # battery life optimizations (install and forget)
      - unzip # oposite of zip
      - usbutils # lsusb
      - neovim # vim on steroids
      - youtube-dl # download videos from the net
      - zsh # shell

- name: TERMINAL - Install app groups
  include_tasks: "groups/{{ item }}.yaml"
  tags: always
  loop: 
    - ansible
    - docker
    - networking
    - virtualisation

- name: TERMINAL - Setup app tasks
  include_tasks: "app_tasks/{{ item }}.yaml"
  tags: always
  loop: 
    - syncthing
    - terminal