- name: remove default apps
  pacman:
    name:
      - okular
      - skanlite
      - konversation
      - kget
      - thunderbird
      - cantata
      - k3b
      - kcalc
      - yakuake
    state: absent
  become: true

- name: force remove clashing apps
  pacman:
    name:
      - ttf-hack
    force: yes
    state: absent
  become: true


- name: install user apps
  kewlfft.aur.aur:
    name:
      - ark # archive manager
      - atom # text editor
      - barrier # network kvm software (mouse and keyboard over the network)
      - code # text editor / ide (replacemen of atom?)
      - copyq # TODO: https://copyq.readthedocs.io/en/latest/known-issues.html#on-linux-global-shortcuts-and-pasting-doesn-t-work
      - discord # chat app for gamers
      - dolphin # file explorer
      - firefox # work browser
      - flameshot # screenshot tool
      - freerdp # needed for remmina rdp
      - gns3-server # network virtualisation tool
      - gns3-gui # network virtualisation tool frontend
      - google-chrome # webbrowser
      - google-earth-pro # used for kmz's
      - gparted # gui partition manager
      - gwenview # picture viewer
      - ipscan # angry ip scanner
      - libratbag # service for piper
      - libvncserver # needed for remmina vnc
      - mpv # media player
      - obs-studio # capture screens and devices
      - piper # mouse setting utility
      - powerline-fonts-git # fonts for terminator
      - remmina # remote desktop solution for rdp, vnc,...
      - slack-desktop # native slack app
      - spotify # music duuuuh
      - streamlink # get livestreams in VLC or other client
      - teams # native microsoft teams app
      - teamviewer # remote desktop tool for support cases
      - terminator # terminal emulator
      - ttf-ms-fonts # ms fonts for winbox
      - virt-manager # libvirt gui manager
      - winbox # add winbox app (wine bottled)
      - wireguard-tools # to enable wireguard connections
      - wireshark-qt # packet capture gui

- name: enable services
  service:
    name: "{{ item }}"
    enabled: yes
  become: true
  loop:
    - libvirtd
