- name: install syncthing
  aur:
    name:
      - syncthing
      # - syncthingtray issue with tray
    state: present

# does only generate a new id when needed
- name: generate device id
  command: syncthing -generate=/home/{{ user.name }}/.config/syncthing/
  changed_when: false

- name: print syncthing device id
  command: syncthing -device-id
  register: syncthing_id
  changed_when: false

- name: copy xml file
  template:
    src: syncthing_config.xml.j2
    dest: /home/{{ user.name }}/.config/syncthing/config.xml
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0644

- name: enable systemd service syncthing
  systemd:
    name: syncthing@{{ user.name }}
    state: restarted
    enabled: yes
  become: true

# - name: symlink all directories to the home directory
#   shell: '{{ item }}'
#   args:
#     warn: false
#   loop:
#     - 'ln -sf /home/{{ user.name}}/.dotfiles/.* /home/{{ user.name }}'
#     - 'ln -sf /home/{{ user.name}}/.dotfiles/.config/* /home/{{ user.name}}/.config'
#   ignore_errors: yes
