- import_tasks: system.yml
  tags: system

- import_tasks: user.yaml
  tags: user

- import_tasks: pacman.yaml
  tags: pacman

- import_tasks: terminal.yaml
  tags: terminal

# - import_tasks: graphical.yaml
#   tags: graphical
#
# - import_tasks: syncthing.yaml
#   tags: syncthing
#
# - import_tasks: user_apps.yaml
#   tags: user_apps
