- import_tasks: 01-system.yml
  tags: system

- import_tasks: 02-user.yaml
  tags: user

- import_tasks: 03-pacman.yaml
  tags: pacman

- name: upgrade all packages
  aur:
    upgrade: yes
  tags: upgrade

- import_tasks: 04-terminal.yaml
  tags: terminal

- import_tasks: 05-graphical.yaml
  tags: graphical

- import_tasks: 06-user_apps.yaml
  tags: user_apps

# - import_tasks: 07-syncthing.yaml
#   tags: syncthing

- import_tasks: 08-printing.yml
  tags: printing
