- name: Give passwordless sudo access to wheel group
  copy:
    content: '%wheel ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/wheel
    validate: /usr/sbin/visudo --check --file=%s
  become: true

- name: start & enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - ntpd
    - sshd
  become: true

- name: Install intel-ucode
  pacman:
    name:
      - intel-ucode
    update_cache: yes
  when: ansible_processor[1].find('Intel') != -1
  become: true

- name: Install amd-ucode
  pacman:
    name:
      - amd-ucode
    update_cache: yes
  when: ansible_processor[1].find('Amd') != -1
  become: true

- name: disable compression of makepkg (aur packages)
  lineinfile:
    dest: /etc/makepkg.conf
    regexp: '^PKGEXT='
    line: "PKGEXT='.pkg.tar'"
  become: true

- name: set hostname in file
  copy:
    content: "{{ new_hostname }}"
    dest: /etc/hostname
  become: true

- name: set hostname in hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: ^127.0.1.1
    line: '127.0.1.1 {{ new_hostname }} {{ new_hostname }}.localdomain'
  become: true
