- name: setup ramdisk for btrfs
  lineinfile:
    dest: /mnt/etc/mkinitcpio.conf
    regexp: ^BINARIES
    line: 'BINARIES=(btrfs)'
  when: use_btrfs
  register: ramdisk1

- name: run encryption items for ramdisk if needed
  block:
    - name: create random file for boot decryption
      community.general.filesize:
        path: /mnt/crypto_keyfile.bin
        size: 2 MiB
        source: /dev/urandom
    - name: encrypt drive
      community.crypto.luks_device:
        device: "{{ root_part }}"
        passphrase: "{{ encryption.password }}"
        new_keyfile: /mnt/crypto_keyfile.bin
    - name: setup ramdisk for disk encryption
      lineinfile:
        dest: /mnt/etc/mkinitcpio.conf
        regexp: ^HOOKS=
        line: 'HOOKS=(base udev autodetect modconf block encrypt filesystems keyboard fsck)'
      register: ramdisk2
    - name: setup ramdisk for encryption file
      lineinfile:
        dest: /mnt/etc/mkinitcpio.conf
        regexp: ^FILES=
        line: 'FILES=(/crypto_keyfile.bin)'
      register: ramdisk3
  when: use_encryption

- name: recreate ramdisk
  command: arch-chroot /mnt mkinitcpio -p linux
  when: ramdisk1.changed or ramdisk2.changed or ramdisk3.changed
